"""新增状态和反馈列

Revision ID: aa29e74b48ea
Revises: 
Create Date: 2026-04-24 19:40:08.734706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa29e74b48ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealer_code_mapping', schema=None) as batch_op:
        batch_op.drop_index('uk_code_prefix')

    op.drop_table('dealer_code_mapping')
    with op.batch_alter_table('radar_source_2024', schema=None) as batch_op:
        batch_op.drop_index('dealer_code')
        batch_op.drop_index('idx_radar_dealer_code')

    op.drop_table('radar_source_2024')
    with op.batch_alter_table('dealer_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.drop_constraint('dealers_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('monthly_metrics_11d', schema=None) as batch_op:
        batch_op.alter_column('dealer_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='经销商代码',
               existing_nullable=False)
        batch_op.alter_column('stat_year',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='年',
               existing_nullable=False)
        batch_op.alter_column('stat_month',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='月',
               existing_nullable=False)
        batch_op.alter_column('sales',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='销量',
               existing_nullable=True)
        batch_op.alter_column('potential_customers',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='潜客量',
               existing_nullable=True)
        batch_op.alter_column('test_drives',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='试驾数',
               existing_nullable=True)
        batch_op.alter_column('leads',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='线索量',
               existing_nullable=True)
        batch_op.alter_column('customer_flow',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='客流量',
               existing_nullable=True)
        batch_op.alter_column('defeat_rate',
               existing_type=mysql.DECIMAL(precision=18, scale=6),
               comment=None,
               existing_comment='战败率',
               existing_nullable=True)
        batch_op.alter_column('success_rate',
               existing_type=mysql.DECIMAL(precision=18, scale=6),
               comment=None,
               existing_comment='成交率',
               existing_nullable=True)
        batch_op.alter_column('success_response_time',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='成交响应时间',
               existing_nullable=True)
        batch_op.alter_column('defeat_response_time',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='战败响应时间',
               existing_nullable=True)
        batch_op.alter_column('policy',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='政策',
               existing_nullable=True)
        batch_op.alter_column('gsev',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='GSEV',
               existing_nullable=True)
        batch_op.drop_index('idx_dealer_code')
        batch_op.drop_index('idx_year_month')
        batch_op.drop_index('uq_dealer_year_month')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('monthly_radar_scores', schema=None) as batch_op:
        batch_op.alter_column('dealer_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment=None,
               existing_comment='经销商代码',
               existing_nullable=False)
        batch_op.alter_column('stat_year',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='年',
               existing_nullable=False)
        batch_op.alter_column('stat_month',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='月',
               existing_nullable=False)
        batch_op.alter_column('spread_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='传播获客力',
               existing_nullable=True)
        batch_op.alter_column('experience_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='体验力',
               existing_nullable=True)
        batch_op.alter_column('conversion_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='转化力',
               existing_nullable=True)
        batch_op.alter_column('service_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='服务力',
               existing_nullable=True)
        batch_op.alter_column('operation_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment=None,
               existing_comment='经营力',
               existing_nullable=True)
        batch_op.drop_index('idx_radar_scores_dealer_code')
        batch_op.drop_index('idx_radar_scores_year_month')
        batch_op.drop_index('uq_radar_dealer_year_month')
        batch_op.drop_column('calc_version')
        batch_op.drop_column('source_tag')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_radar_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='生成时间'))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'))
        batch_op.add_column(sa.Column('source_tag', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='数据来源标识'))
        batch_op.add_column(sa.Column('calc_version', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='计算版本号'))
        batch_op.create_index('uq_radar_dealer_year_month', ['dealer_code', 'stat_year', 'stat_month'], unique=True)
        batch_op.create_index('idx_radar_scores_year_month', ['stat_year', 'stat_month'], unique=False)
        batch_op.create_index('idx_radar_scores_dealer_code', ['dealer_code'], unique=False)
        batch_op.alter_column('operation_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='经营力',
               existing_nullable=True)
        batch_op.alter_column('service_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='服务力',
               existing_nullable=True)
        batch_op.alter_column('conversion_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='转化力',
               existing_nullable=True)
        batch_op.alter_column('experience_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='体验力',
               existing_nullable=True)
        batch_op.alter_column('spread_force',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='传播获客力',
               existing_nullable=True)
        batch_op.alter_column('stat_month',
               existing_type=mysql.INTEGER(),
               comment='月',
               existing_nullable=False)
        batch_op.alter_column('stat_year',
               existing_type=mysql.INTEGER(),
               comment='年',
               existing_nullable=False)
        batch_op.alter_column('dealer_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment='经销商代码',
               existing_nullable=False)

    with op.batch_alter_table('monthly_metrics_11d', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='导入时间'))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'))
        batch_op.create_index('uq_dealer_year_month', ['dealer_code', 'stat_year', 'stat_month'], unique=True)
        batch_op.create_index('idx_year_month', ['stat_year', 'stat_month'], unique=False)
        batch_op.create_index('idx_dealer_code', ['dealer_code'], unique=False)
        batch_op.alter_column('gsev',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='GSEV',
               existing_nullable=True)
        batch_op.alter_column('policy',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='政策',
               existing_nullable=True)
        batch_op.alter_column('defeat_response_time',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='战败响应时间',
               existing_nullable=True)
        batch_op.alter_column('success_response_time',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='成交响应时间',
               existing_nullable=True)
        batch_op.alter_column('success_rate',
               existing_type=mysql.DECIMAL(precision=18, scale=6),
               comment='成交率',
               existing_nullable=True)
        batch_op.alter_column('defeat_rate',
               existing_type=mysql.DECIMAL(precision=18, scale=6),
               comment='战败率',
               existing_nullable=True)
        batch_op.alter_column('customer_flow',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='客流量',
               existing_nullable=True)
        batch_op.alter_column('leads',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='线索量',
               existing_nullable=True)
        batch_op.alter_column('test_drives',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='试驾数',
               existing_nullable=True)
        batch_op.alter_column('potential_customers',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='潜客量',
               existing_nullable=True)
        batch_op.alter_column('sales',
               existing_type=mysql.DECIMAL(precision=18, scale=4),
               comment='销量',
               existing_nullable=True)
        batch_op.alter_column('stat_month',
               existing_type=mysql.INTEGER(),
               comment='月',
               existing_nullable=False)
        batch_op.alter_column('stat_year',
               existing_type=mysql.INTEGER(),
               comment='年',
               existing_nullable=False)
        batch_op.alter_column('dealer_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50),
               comment='经销商代码',
               existing_nullable=False)

    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('dealers_ibfk_1', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('dealer_task', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('progress')

    op.create_table('radar_source_2024',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dealer_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=False, comment='经销商代码'),
    sa.Column('province', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True, comment='省份'),
    sa.Column('fed_level', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True, comment='销售FED级别'),
    sa.Column('terminal_check_avg', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='终端检核平均分'),
    sa.Column('customer_flow_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量1月'),
    sa.Column('customer_flow_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量2月'),
    sa.Column('customer_flow_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量3月'),
    sa.Column('customer_flow_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量4月'),
    sa.Column('customer_flow_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量5月'),
    sa.Column('customer_flow_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量6月'),
    sa.Column('customer_flow_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量7月'),
    sa.Column('customer_flow_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量8月'),
    sa.Column('customer_flow_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量9月'),
    sa.Column('customer_flow_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='客流量10月'),
    sa.Column('potential_customers_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量1月'),
    sa.Column('potential_customers_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量2月'),
    sa.Column('potential_customers_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量3月'),
    sa.Column('potential_customers_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量4月'),
    sa.Column('potential_customers_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量5月'),
    sa.Column('potential_customers_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量6月'),
    sa.Column('potential_customers_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量7月'),
    sa.Column('potential_customers_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量8月'),
    sa.Column('potential_customers_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量9月'),
    sa.Column('potential_customers_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='潜客量10月'),
    sa.Column('leads_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量1月'),
    sa.Column('leads_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量2月'),
    sa.Column('leads_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量3月'),
    sa.Column('leads_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量4月'),
    sa.Column('leads_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量5月'),
    sa.Column('leads_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量6月'),
    sa.Column('leads_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量7月'),
    sa.Column('leads_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量8月'),
    sa.Column('leads_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量9月'),
    sa.Column('leads_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='线索量10月'),
    sa.Column('success_rate_m01', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率1月'),
    sa.Column('success_rate_m02', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率2月'),
    sa.Column('success_rate_m03', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率3月'),
    sa.Column('success_rate_m04', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率4月'),
    sa.Column('success_rate_m05', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率5月'),
    sa.Column('success_rate_m06', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率6月'),
    sa.Column('success_rate_m07', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率7月'),
    sa.Column('success_rate_m08', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率8月'),
    sa.Column('success_rate_m09', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率9月'),
    sa.Column('success_rate_m10', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='成交率10月'),
    sa.Column('defeat_rate_m01', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率1月'),
    sa.Column('defeat_rate_m02', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率2月'),
    sa.Column('defeat_rate_m03', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率3月'),
    sa.Column('defeat_rate_m04', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率4月'),
    sa.Column('defeat_rate_m05', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率5月'),
    sa.Column('defeat_rate_m06', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率6月'),
    sa.Column('defeat_rate_m07', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率7月'),
    sa.Column('defeat_rate_m08', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率8月'),
    sa.Column('defeat_rate_m09', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率9月'),
    sa.Column('defeat_rate_m10', mysql.DECIMAL(precision=18, scale=6), nullable=True, comment='战败率10月'),
    sa.Column('sales_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量1月'),
    sa.Column('sales_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量2月'),
    sa.Column('sales_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量3月'),
    sa.Column('sales_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量4月'),
    sa.Column('sales_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量5月'),
    sa.Column('sales_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量6月'),
    sa.Column('sales_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量7月'),
    sa.Column('sales_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量8月'),
    sa.Column('sales_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量9月'),
    sa.Column('sales_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='销量10月'),
    sa.Column('success_response_time_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间1月'),
    sa.Column('success_response_time_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间2月'),
    sa.Column('success_response_time_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间3月'),
    sa.Column('success_response_time_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间4月'),
    sa.Column('success_response_time_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间5月'),
    sa.Column('success_response_time_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间6月'),
    sa.Column('success_response_time_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间7月'),
    sa.Column('success_response_time_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间8月'),
    sa.Column('success_response_time_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间9月'),
    sa.Column('success_response_time_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='成交响应时间10月'),
    sa.Column('defeat_response_time_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间1月'),
    sa.Column('defeat_response_time_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间2月'),
    sa.Column('defeat_response_time_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间3月'),
    sa.Column('defeat_response_time_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间4月'),
    sa.Column('defeat_response_time_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间5月'),
    sa.Column('defeat_response_time_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间6月'),
    sa.Column('defeat_response_time_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间7月'),
    sa.Column('defeat_response_time_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间8月'),
    sa.Column('defeat_response_time_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间9月'),
    sa.Column('defeat_response_time_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='战败响应时间10月'),
    sa.Column('test_drives_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数1月'),
    sa.Column('test_drives_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数2月'),
    sa.Column('test_drives_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数3月'),
    sa.Column('test_drives_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数4月'),
    sa.Column('test_drives_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数5月'),
    sa.Column('test_drives_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数6月'),
    sa.Column('test_drives_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数7月'),
    sa.Column('test_drives_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数8月'),
    sa.Column('test_drives_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数9月'),
    sa.Column('test_drives_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='试驾数10月'),
    sa.Column('policy_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策1月'),
    sa.Column('policy_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策2月'),
    sa.Column('policy_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策3月'),
    sa.Column('policy_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策4月'),
    sa.Column('policy_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策5月'),
    sa.Column('policy_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策6月'),
    sa.Column('policy_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策7月'),
    sa.Column('policy_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策8月'),
    sa.Column('policy_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策9月'),
    sa.Column('policy_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='政策10月'),
    sa.Column('gsev_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV1月'),
    sa.Column('gsev_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV2月'),
    sa.Column('gsev_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV3月'),
    sa.Column('gsev_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV4月'),
    sa.Column('gsev_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV5月'),
    sa.Column('gsev_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV6月'),
    sa.Column('gsev_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV7月'),
    sa.Column('gsev_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV8月'),
    sa.Column('gsev_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV9月'),
    sa.Column('gsev_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='GSEV10月'),
    sa.Column('evaluation_score_m01', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分1月'),
    sa.Column('evaluation_score_m02', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分2月'),
    sa.Column('evaluation_score_m03', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分3月'),
    sa.Column('evaluation_score_m04', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分4月'),
    sa.Column('evaluation_score_m05', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分5月'),
    sa.Column('evaluation_score_m06', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分6月'),
    sa.Column('evaluation_score_m07', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分7月'),
    sa.Column('evaluation_score_m08', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分8月'),
    sa.Column('evaluation_score_m09', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分9月'),
    sa.Column('evaluation_score_m10', mysql.DECIMAL(precision=18, scale=4), nullable=True, comment='评价分10月'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='导入时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('radar_source_2024', schema=None) as batch_op:
        batch_op.create_index('idx_radar_dealer_code', ['dealer_code'], unique=False)
        batch_op.create_index('dealer_code', ['dealer_code'], unique=True)

    op.create_table('dealer_code_mapping',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code_prefix', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), nullable=False),
    sa.Column('province', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('dealer_code_mapping', schema=None) as batch_op:
        batch_op.create_index('uk_code_prefix', ['code_prefix'], unique=True)

    # ### end Alembic commands ###
